version: '3.7'

services:
  hpilo:
    image: idnt/hpilo-exporter:latest
    ports:
      - 9416:9416
    command:
      - '--port=9416'
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      #          - node.hostname == my_node.domain
