apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  labels:
    machine.openshift.io/cluster-api-cluster: ts-3-m7x7b
    machine.openshift.io/cluster-api-machine-role: worker
    machine.openshift.io/cluster-api-machine-type: worker
  name: ts-3-m7x7b-worker
  namespace: openshift-machine-api
spec:
  replicas: 1
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: ts-3-m7x7b
      machine.openshift.io/cluster-api-machineset: ts-3-m7x7b-worker
  template:
    metadata:
      labels:
        machine.openshift.io/cluster-api-cluster: ts-3-m7x7b
        machine.openshift.io/cluster-api-machine-role: worker
        machine.openshift.io/cluster-api-machine-type: worker
        machine.openshift.io/cluster-api-machineset: ts-3-m7x7b-worker
    spec:
      providerSpec:
        value:
          apiVersion: openstackproviderconfig.openshift.io/v1alpha1
          kind: OpenstackProviderSpec
          cloudName: openstack
          cloudsSecret:
            name: openstack-cloud-credentials
            namespace: openshift-machine-api
          flavor: s4c-8gb-60
          image: ts-3-fcos
          primarySubnet: b0b61b55-24cb-4e3d-abfd-dc3d188265f5
          securityGroups:
          - name: common
          serverMetadata:
            Name: ts-3-m7x7b-worker
            openshiftClusterID: ts-3-m7x7b
          tags:
          - openshiftClusterID=ts-3-m7x7b
          userDataSecret:
            name: worker-user-data
