---
- name: Initializing master node
  hosts: master
  #  remote_user: ubuntu
  #  become_method: sudo
  #  become: yes
  #vars:
  #  masterIP: 10.12.7.60
  roles:
    - swap-off
    - apt-tls
    - docker
    - kube
    - init-kube-master
