apiVersion: v1
kind: Pod
metadata:
 name: nfs
spec:
 containers:
 - name: nfs
   image: ubuntu
   volumeMounts:
   - name: nfs
     mountPath: "/data-mount"

 volumes:
 - name: nfs
   nfs:
     server: 10.12.7.59
     path: "/mnt/share"
