---
- name: hello
  hosts: webservers
  remote_user: ubuntu
  become_method: sudo
  become: yes
  vars:
   http_port: 80
   max_client: 200
  tasks:
  - name: installing docker
    apt:
     name: docker.io
     state: latest

  - name: installing mysql
    apt: name=mysql-server state=latest


  - name: commands
    command: echo sth
    
  - name: run local script on remote/dest
    script: sth.sh --somearge 1 2 3
    args:
      chdir: /home

  - name: copy scp
    copy: src=/path/to/source/on/local  dest=/path/to/remote/dest
    
    
  - name: service restart
    service: name=nginx state=restarted
    
    
 - name: service 
 
 
 
