#!/bin/bash
a=0
b=0
c=''
while getopts 'abc:' opt; do
	case $opt in
		a) a=1;;
		b) b=1;;
		c) c=$OPTARG;;
		?)
			echo "script usage: $(basename $0) [-l] [-h] [-a somevalue]" >&2
			exit 1
			;;
	esac
done

echo "a: $a  b: $b  c: $c"
exit 0
