version: "3.7"

services:
  blackbox-exporter:
    image: prom/blackbox-exporter:master
    ports:
    - 9115:9115
    configs:
      - source: blackbox-conf
        target: /blackbox.yml
    command: '--config.file=/blackbox.yml'

configs:
  blackbox-conf:
    file: ./blackbox.conf
