apiVersion: apps/v1
kind: Deployment
metadata:
 name: nginx
 labels:
   project: pilot
   environment: staging
   tier: frontend
spec:
 selector:
   matchLabels:
     app: nginx
 replicas: 2
 template:
   metadata:
     labels:
       app: nginx
   spec:
     containers:
     - name: nginx
       image: nginx
       imagePullPolicy: IfNotPresent
       volumeMounts:
       - name: pv
         mountPath: "/usr/share/nginx/html"
       ports:
       - containerPort: 80
     volumes:
     - name: pv
       persistentVolumeClaim:
         claimName: "pvclaim01"
