{{- range $team := .Values.teams }}
{{- range $ns := $team.namespaces }}
---
apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
  name: {{ $ns.name }}
  namespace: {{ $.Release.Namespace }}
spec:
  name: {{ $ns.name }}.yaml
  datasources:
    - name: {{ $ns.name }}
      type: prometheus
      access: proxy
      url: https://thanos-querier-custom.openshift-monitoring.svc.cluster.local:9092
      isDefault: false
      version: 1
      editable: false
      orgId: {{ $team.orgId }}
      jsonData:
        tlsSkipVerify: true
        customQueryParameters: namespace={{ $ns.name }}
        httpMethod: GET
        httpHeaderName1: Authorization
      secureJsonData:
        httpHeaderValue1: Bearer {{ $ns.token }}
{{- end }}
{{- end }}
