route:
  receiver: 'dev_null'
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  group_by: [cluster, alertname]
  # All alerts that do not match the following child routes
  # will remain at the root node and be dispatched to 'default-receiver'.
  routes:
  - receiver: 'sepino-rocketchat'
    match:
      job: 'critical nodes'
      severity: critical
          #  org: sepino


# Inhibition rules allow to mute a set of alerts given that another alert is
# firing. We use this to mute any warning-level notifications if the same
# alert is already critical.
inhibit_rules:
- source_match:
    severity: 'critical'
  target_match:
    severity: 'warning'
  # Apply inhibition if the alertname is the same.
  equal: ['alertname']

receivers:
  - name: 'dev_null'

  - name: 'sepino-rocketchat'
    webhook_configs:
      - send_resolved: false
        url: 'https://chat.hasin.ir/hooks/ESqu8xorgwRgm9Gam/QsYFTTuJnFWuhjtR8XPFJhiSonDFFD4bjdRTCDuiY3QNdrTM'
