groups:
- name: AllInstances
  rules:
  - alert: InstanceDown
    expr: up == 0
    for: 1m
    # Annotation - additional informational labels to store more information
    annotations:
      title: 'Instance {{ $labels.instance }} down'
      description: '{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 1 minute.'
   # Labels - additional labels to be attached to the alert
    labels:
      severity: 'critical'

- name: Critical Monitoring Class
  rules:
  - alert: InstanceDown
    expr: up == 0
    for: 1m
    labels:
      severity: 'critical'


  - alert: CPU
    expr: avg(irate(node_cpu_seconds_total{mode="idle"}[30m])) by (instance) < 0.1 #availabe cpu percentage
    for: 20m
    labels:
      severity: 'critical'

  - alert: RAM
    expr: ((avg_over_time(node_memory_MemFree_bytes[10m]) + avg_over_time(node_memory_Cached_bytes[10m]) + avg_over_time(node_memory_Buffers_bytes[10m])) / avg_over_time(node_memory_MemTotal_bytes[10m])) < 0.1 #percent available memory
    for: 20m
    labels:
      severity: 'critical'

  - alert: Disk
    expr: (node_filesystem_free_bytes{fstype=~"ext4|xfs"} / node_filesystem_size_bytes{fstype=~"ext4|xfs"}) < 0.1 #percent available FS 
    for: 20m
    labels:
      severity: 'critical'

  - alert: Uptime
    expr: sum(time() - node_boot_time_seconds)
    for: 20m
    labels:
      severity: 'critical'





